[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "viopi"
version = "0.4.0"
dependencies = [
    "python-magic",
]
description = "Saves command output and shows statistics on it."
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Topic :: Utilities",
]

[project.scripts]
viopi = "viopi.main:main"

[tool.setuptools.packages.find]
where = [
    "src",
]
